AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: amendements-extractor

Resources:
  extractor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(40 * * * ? *)
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          MONGO_URL: __MONGO_URL__
          MONGO_DB: __MONGO_DB__
